---

    - name: view vimplug
      stat:
          path: "/root/.local/share/nvim/site/autoload/plug.vim"
      register: file_data

    - name: install vimplug
      ansible.builtin.shell:
        cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      when: not file_data.stat.exists

    - name: if exists nvim config
      stat:
        path: "/root/.config/nvim/init.vim"
      register: file_data

    - name: config neovim
      ansible.builtin.shell:
        cmd: curl -fLo /root/.config/nvim/init.vim --create-dirs https://raw.githubusercontent.com/vmath3us/arch-start/main/init.vim
      when: not file_data.stat.exists
